apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prod-gitopsdemo
  namespace: prod-gitopsdemo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:prod-*
spec:
  releaseName: prod-gitopsdemo
  chart:
    git: git@github.com:idobry/devopsutils.git
    path: charts/gitopsdemo
    ref: master
