---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: e2e-gitopsdemo
  namespace: e2e
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:e2e-*
spec:
  releaseName: e2e-gitopsdemo
  chart:
    git: git@github.com:idobry/devopsutils.git
    path: charts/gitopsdemo
    ref: master
  values:
    image: idobry/gitopsdemo:e2e-4497de0-195
    environment: e2e
    nodePort: 30004
