---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stage-gitopsdemo
  namespace: stage-gitopsdemo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stage-*
spec:
  releaseName: stage-gitopsdemo
  chart:
    git: git@github.com:idobry/devopsutils.git
    path: charts/gitopsdemo
    ref: master
  values:
    image: idobry/gitopsdemo:stage-bfbad21-197
    environment: stage
    service:
      nodePort: 30002
