replicaCount: 1
environment: stage
image: idobry/gitopsdemo:stage-4368178-186
pullPolicy: Always
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 30000
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
